# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.27

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/local/bin/cmake

# The command to remove a file.
RM = /usr/local/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/hwndrer/kurs_os

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/hwndrer/kurs_os

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "No interactive CMake dialog available..."
	/usr/local/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake to regenerate build system..."
	/usr/local/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/hwndrer/kurs_os/CMakeFiles /home/hwndrer/kurs_os//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/hwndrer/kurs_os/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named main

# Build rule for target.
main: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 main
.PHONY : main

# fast build rule for target.
main/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/build
.PHONY : main/fast

main.o: main.cpp.o
.PHONY : main.o

# target to build an object file
main.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/main.cpp.o
.PHONY : main.cpp.o

main.i: main.cpp.i
.PHONY : main.i

# target to preprocess a source file
main.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/main.cpp.i
.PHONY : main.cpp.i

main.s: main.cpp.s
.PHONY : main.s

# target to generate assembly for a file
main.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/main.cpp.s
.PHONY : main.cpp.s

src/bitmap.o: src/bitmap.cpp.o
.PHONY : src/bitmap.o

# target to build an object file
src/bitmap.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/src/bitmap.cpp.o
.PHONY : src/bitmap.cpp.o

src/bitmap.i: src/bitmap.cpp.i
.PHONY : src/bitmap.i

# target to preprocess a source file
src/bitmap.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/src/bitmap.cpp.i
.PHONY : src/bitmap.cpp.i

src/bitmap.s: src/bitmap.cpp.s
.PHONY : src/bitmap.s

# target to generate assembly for a file
src/bitmap.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/src/bitmap.cpp.s
.PHONY : src/bitmap.cpp.s

src/clear.o: src/clear.cpp.o
.PHONY : src/clear.o

# target to build an object file
src/clear.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/src/clear.cpp.o
.PHONY : src/clear.cpp.o

src/clear.i: src/clear.cpp.i
.PHONY : src/clear.i

# target to preprocess a source file
src/clear.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/src/clear.cpp.i
.PHONY : src/clear.cpp.i

src/clear.s: src/clear.cpp.s
.PHONY : src/clear.s

# target to generate assembly for a file
src/clear.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/src/clear.cpp.s
.PHONY : src/clear.cpp.s

src/console.o: src/console.cpp.o
.PHONY : src/console.o

# target to build an object file
src/console.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/src/console.cpp.o
.PHONY : src/console.cpp.o

src/console.i: src/console.cpp.i
.PHONY : src/console.i

# target to preprocess a source file
src/console.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/src/console.cpp.i
.PHONY : src/console.cpp.i

src/console.s: src/console.cpp.s
.PHONY : src/console.s

# target to generate assembly for a file
src/console.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/src/console.cpp.s
.PHONY : src/console.cpp.s

src/executor.o: src/executor.cpp.o
.PHONY : src/executor.o

# target to build an object file
src/executor.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/src/executor.cpp.o
.PHONY : src/executor.cpp.o

src/executor.i: src/executor.cpp.i
.PHONY : src/executor.i

# target to preprocess a source file
src/executor.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/src/executor.cpp.i
.PHONY : src/executor.cpp.i

src/executor.s: src/executor.cpp.s
.PHONY : src/executor.s

# target to generate assembly for a file
src/executor.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/src/executor.cpp.s
.PHONY : src/executor.cpp.s

src/exit.o: src/exit.cpp.o
.PHONY : src/exit.o

# target to build an object file
src/exit.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/src/exit.cpp.o
.PHONY : src/exit.cpp.o

src/exit.i: src/exit.cpp.i
.PHONY : src/exit.i

# target to preprocess a source file
src/exit.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/src/exit.cpp.i
.PHONY : src/exit.cpp.i

src/exit.s: src/exit.cpp.s
.PHONY : src/exit.s

# target to generate assembly for a file
src/exit.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/src/exit.cpp.s
.PHONY : src/exit.cpp.s

src/fs.o: src/fs.cpp.o
.PHONY : src/fs.o

# target to build an object file
src/fs.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/src/fs.cpp.o
.PHONY : src/fs.cpp.o

src/fs.i: src/fs.cpp.i
.PHONY : src/fs.i

# target to preprocess a source file
src/fs.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/src/fs.cpp.i
.PHONY : src/fs.cpp.i

src/fs.s: src/fs.cpp.s
.PHONY : src/fs.s

# target to generate assembly for a file
src/fs.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/src/fs.cpp.s
.PHONY : src/fs.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... main"
	@echo "... main.o"
	@echo "... main.i"
	@echo "... main.s"
	@echo "... src/bitmap.o"
	@echo "... src/bitmap.i"
	@echo "... src/bitmap.s"
	@echo "... src/clear.o"
	@echo "... src/clear.i"
	@echo "... src/clear.s"
	@echo "... src/console.o"
	@echo "... src/console.i"
	@echo "... src/console.s"
	@echo "... src/executor.o"
	@echo "... src/executor.i"
	@echo "... src/executor.s"
	@echo "... src/exit.o"
	@echo "... src/exit.i"
	@echo "... src/exit.s"
	@echo "... src/fs.o"
	@echo "... src/fs.i"
	@echo "... src/fs.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

